/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinMatchRouteImport } from './routes/join-match'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreateMatchRouteImport } from './routes/create-match'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinMatchRoute = JoinMatchRouteImport.update({
  id: '/join-match',
  path: '/join-match',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMatchRoute = CreateMatchRouteImport.update({
  id: '/create-match',
  path: '/create-match',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-match': typeof CreateMatchRoute
  '/history': typeof HistoryRoute
  '/join-match': typeof JoinMatchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-match': typeof CreateMatchRoute
  '/history': typeof HistoryRoute
  '/join-match': typeof JoinMatchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-match': typeof CreateMatchRoute
  '/history': typeof HistoryRoute
  '/join-match': typeof JoinMatchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-match'
    | '/history'
    | '/join-match'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/profile'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-match'
    | '/history'
    | '/join-match'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/profile'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/create-match'
    | '/history'
    | '/join-match'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/profile'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateMatchRoute: typeof CreateMatchRoute
  HistoryRoute: typeof HistoryRoute
  JoinMatchRoute: typeof JoinMatchRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-match': {
      id: '/join-match'
      path: '/join-match'
      fullPath: '/join-match'
      preLoaderRoute: typeof JoinMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-match': {
      id: '/create-match'
      path: '/create-match'
      fullPath: '/create-match'
      preLoaderRoute: typeof CreateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateMatchRoute: CreateMatchRoute,
  HistoryRoute: HistoryRoute,
  JoinMatchRoute: JoinMatchRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
